config/routes.rb
Rails.application.routes.draw do

  root 'github_accounts#index'

  get 'github_accounts' => 'github_accounts#index'
  get 'github_accounts/:id' => 'github_accounts#show', as: 'github_account'

end

app/models/github_account.rb
require 'open-uri'

class GithubAccount

  def initialize(account)
    begin
      @user_info = Octokit.user account
    rescue
      @user_info
    end
  end

  def user_info
    @user_info
  end

  def fetch_user_repos
    if user_info.present?
      if self.user_info.repos_url.present?
        JSON.load(open(self.user_info.repos_url))
      end
    end
  end

  def repo_languages
    languages = []
    user_repos = self.fetch_user_repos
      if user_repos.present?
      user_repos.each do |r|
        languages << r["language"]
      end
    end

    languages
  end

  def repo_language_counts
    languages = self.repo_languages.each_with_object(Hash.new(0)) { |count, language| language[count] += 1 }
    languages.sort_by {|language,count| count}.reverse
  end

  protected :fetch_user_repos, :repo_languages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_accounts_controller.rb
class GithubAccountsController < ApplicationController

  # GET /github_accounts
  def index
    if params[:query] && params[:query] != ""
  			@account = GithubAccount.new(params[:query])
			if @account.present?
        if @account.user_info.present?
			    redirect_to :action => "show", :id => params[:query]
        else
          flash.now.notice = "We can't find this GitHub account. Maybe it doesn't exist or maybe Github is currently inaccessible."
        end
			end
    end
  end

  # GET /github_accounts/1
  def show
      @account = GithubAccount.new(params[:id])

      if @account.user_info == nil
        flash.now.notice = "We can't find this GitHub account. Maybe it doesn't exist or maybe Github is currently inaccessible."
      end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_accounts_helper.rb
module GithubAccountsHelper
end

app/views/github_accounts/index.html.erb
<h1>GitHub Account Lookup</h1>
<%= form_tag github_accounts_path, :method => 'get' do %>
	<div>
		<%= text_field_tag :query, params[:query] %>
		<%= submit_tag "Search", :name => nil %>
	</div>
	<br/>
<% end %>

app/views/github_accounts/show.html.erb
<p>
  <% if @account.present? %>
    <% if @account.user_info.present? %>
      <h1>Language Summary for <%= @account.user_info.login %>:</h1>
      <div id="language_info">
        <% @account.repo_language_counts.each do |l| %>
          <p>
            <% if l[0].present? %>
              <%= l[1] %> repo(s) using mainly <%= l[0] %>
            <% else %>
              <%= l[1] %> repo(s) using mainly an unknown language
            <% end %>
          </p>
        <% end %>
      </div>
      <div id="language_most_common">
        <p>
          <% if @account.repo_language_counts[0][0].present? %>
            Maybe <%= @account.repo_language_counts[0][0] %> is their favorite language?
          <% else %>
            Maybe an unknown language is their favorite?
          <% end %>
        </p>
      </div>
    <% end %>
  <% end %>
</p>
<br/>
<%= link_to 'Try another', github_accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sh24 Exercise 1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>